version: 0.2

env:
  git-credential-helper: yes

phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - npm install -g pnpm
      - pnpm --version
      - pnpm install
  build:
    commands:
      - pnpm run build

artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    website:
      files:
        - 'frontend/website/public/**/*'
      name: website